import Head from 'next/head'
import React from 'react'

export default function Home () {
  return (
    <div>
      <Head>
        <title>Alex Ramírez</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Main is the main view where content gets rendered. The padding is controlled ideally here. */}
      <main className='px-4 sm:px-8 lg:px-24'>
        <div>This is my about page</div>
      </main>
    </div>
  )
}
